name: Test

on:
  workflow_dispatch:

jobs:
  run-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: manjaro-kernels/kernel-action@exp
        with:
          gitlab-pw: ${{ secrets.gitlab_server_user }}
          build-mirror: ${{ secrets.BUILD_MIRROR }}
          branch: unstable
          bump-kernel: false
          bump-modules: repo
          gpg-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          boxit-host: ${{ secrets.BOXIT_HOST }}
          boxit-target: ${{ secrets.BOXIT_TARGET }}
          ssh-key: ${{ secrets.SSH_PACKAGE_CI }}
